### ISSUE TITLE
Vimeo video exception when get direct link

### ISSUE THREAD

**Issue by trungptdhcn** [axet/wget#4]
I using your library to extract direct link from vimeo but when i run your example it have exception: 

<b>Exception in thread "main" com.github.axet.wget.info.ex.DownloadError: unknown config vimeo respond
	at com.github.axet.vget.vhs.VimeoParser.extractLinks(VimeoParser.java:159)
	at com.github.axet.vget.vhs.VimeoParser.extract(VimeoParser.java:208)
	at com.github.axet.vget.info.VGetParser.info(VGetParser.java:16)
	at com.github.axet.vget.VGet.extract(VGet.java:293)
	at com.github.axet.vget.AppManagedDownload.run(AppManagedDownload.java:103)
	at com.github.axet.vget.AppManagedDownload.main(AppManagedDownload.java:122)
	at com.github.axet.vget.VimeoTest.main(VimeoTest.java:6)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
</b> I trying debug but I can't get reason for this problem. Please help me reslove it

**Comment by axet** [comment]
It seems Vimeo blocks the video download. Maybe you can find some plugin / script somewhere in internet which solves the issue.

**Comment by trungptdhcn** [comment]
Ok I will check this. Thank for suguestion
